// 
// Generated by @himenon/openapi-typescript-code-generator v0.9.0
// 
// OpenApi : 3.0.3
// 
// License  : MIT
// 


export namespace Schemas {
    export interface Author {
        id: string;
        /** author name */
        name: string;
    }
    /** Book Model */
    export interface Book {
        title: string;
        author: Schemas.Author;
        ISBN: string;
        publishAt: string;
        updatedAt: string;
    }
}
export namespace Responses {
    /** Get Books */
    export namespace Books {
        export interface Content {
            "application/json": {
                books: Schemas.Book[];
            };
        }
    }
}
